#  <font color='blue'>Data Science Academy </font>

# <font color='blue'>Big Data Real-time Analytics com Python e Spark </font>

## Concatenaçao join e split de arrays com Numpy

In [1]:
import sys
import numpy as np
print(sys.version)
np.__version__

3.8.5 (default, Sep  4 2020, 02:22:02) 
[Clang 10.0.0 ]


'1.19.2'

## Concatenando arrays

In [2]:
array1 = np.ones(4)

In [3]:
array2 = np.arange(15)

In [6]:
array_conc = np.concatenate((array1, array2))

In [8]:
array_conc

array([ 1.,  1.,  1.,  1.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,
        9., 10., 11., 12., 13., 14.])

## Join de arrays

In [10]:
a = np.ones((3,3))
b = np.zeros((3,3))

In [11]:
?np.vstack

Signature: np.vstack(tup)
Docstring:
Stack arrays in sequence vertically (row wise).

This is equivalent to concatenation along the first axis after 1-D arrays
of shape `(N,)` have been reshaped to `(1,N)`. Rebuilds arrays divided by
`vsplit`.

This function makes most sense for arrays with up to 3 dimensions. For
instance, for pixel-data with a height (first axis), width (second axis),
and r/g/b channels (third axis). The functions `concatenate`, `stack` and
`block` provide more general stacking and concatenation operations.

Parameters
----------
tup : sequence of ndarrays
    The arrays must have the same shape along all but the first axis.
    1-D arrays must have the same length.

Returns
-------
stacked : ndarray
    The array formed by stacking the given arrays, will be at least 2-D.

See Also
--------
concatenate : Join a sequence of arrays along an existing axis.
stack : Join a sequence of arrays along a new axis.
block : Assemble an nd-array from nested lists of blocks.
hstac

In [12]:
# preenche primeiro as linhas
np.vstack((a,b))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
# preenche primeiro as colunas
np.hstack((a,b))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [15]:
# Joing de arrays
a = np.array([0,1,2])
b = np.array([3,4,5])
c = np.array([6,7,8])

In [18]:
np.column_stack((a,b,c))

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [19]:
np.row_stack((a,b,b))

array([[0, 1, 2],
       [3, 4, 5],
       [3, 4, 5]])

## Split de arrays

In [21]:
array3 = np.arange(16).reshape((4,4)); array3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [23]:
[array3_p1, array3_p2] = np.hsplit(array3, 2)

In [24]:
array3_p1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [25]:
array3_p2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [26]:
[array3_p1, array3_p2] = np.vsplit(array3, 2)

In [27]:
array3_p1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [28]:
array3_p2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

## Gravando e carregando dados com numpy

In [29]:
dados = array3

In [30]:
np.save('sados_saved_v1', dados)

In [33]:
dados2 = np.load('sados_saved_v1.npy')

In [34]:
dados2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])