#  <font color='blue'>Data Science Academy </font>

# <font color='blue'>Big Data Real-time Analytics com Python e Spark </font>

## Numpy

Numpy oferece uma sequencia de elementos que são mais eficientes que sequencias padroes 

In [1]:
import sys
import numpy as np
print(sys.version)
np.__version__

3.8.5 (default, Sep  4 2020, 02:22:02) 
[Clang 10.0.0 ]


'1.19.2'

In [2]:
# criando array com arrange
array1 = np.arange(15)

In [3]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
array1.mean()

7.0

In [5]:
array1.sum()

105

In [6]:
array1.min()

0

In [7]:
array1.max()

14

In [8]:
array1.std()

4.320493798938574

# Utilizando Lista comprehension com arrays numpy

In [9]:
[x for x in array1]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [11]:
[x * x for x in array1 if x % 2 == 0]

[0, 4, 16, 36, 64, 100, 144, 196]

# Utilizando funções lambda com arrays numpy

In [12]:
list(filter(lambda x: x % 2 == 0, array1))

[0, 2, 4, 6, 8, 10, 12, 14]

In [13]:
array1 % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True])

In [15]:
array1[array1 % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

# Avaliando performance

In [19]:
# performance usando list comprehension
%timeit [ x for x in array1 if x % 2 == 0]

7.49 µs ± 244 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [20]:
%timeit array1[array1 % 2 == 0]

1.92 µs ± 20.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# Usando Operadores Logicos

In [21]:
array1 > 8

array([False, False, False, False, False, False, False, False, False,
        True,  True,  True,  True,  True,  True])

In [22]:
array1[array1 > 8]

array([ 9, 10, 11, 12, 13, 14])

In [23]:
(array1 > 9) & (array1 < 23)

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [24]:
# Operador logico E
array1[(array1 > 9) & (array1 < 23)]

array([10, 11, 12, 13, 14])

In [25]:
# operador logico ou
array1[(array1 > 9) | (array1 < 23)]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
# criando um array numpy com list comprehension
array2 = np.array([x for x in range(15)])

In [27]:
array2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
# usando um array como indice de outro array
array2[array1]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])