#  <font color='blue'>Data Science Academy </font>

# <font color='blue'>Big Data Real-time Analytics com Python e Spark </font>

## Operações matematicas com numpy

A principal vantagem de utilizar matrizes com Numpy, é que esse tipo de objeto possui comvenientes notações para multiplicação de matrizes. Array e Matriz possuem atributo T para retornar a transposta da matriz, possui atributo I para inversa e H (transposta conjugada) 

In [1]:
import sys
import numpy as np
print(sys.version)
np.__version__

3.8.5 (default, Sep  4 2020, 02:22:02) 
[Clang 10.0.0 ]


'1.19.2'

## Criando Matrizes

In [2]:
mat = np.matrix("1,2,3;4,5,6")

In [4]:
print(mat)

[[1 2 3]
 [4 5 6]]


In [5]:
type(mat)

numpy.matrix

In [7]:
mat2 = np.matrix([[1,2,3],[4,5,6]])
print(mat2)

[[1 2 3]
 [4 5 6]]


In [8]:
type(mat2)

numpy.matrix

In [9]:
mat3 = np.matrix([[1,2,3],[4,5,6],[7,8,9],[0,0,0]])
print(mat3)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [0 0 0]]


In [10]:
type(mat3)

numpy.matrix

In [13]:
mat3[2,2]

9

## Operações matematicas com arrays e matrizes

In [14]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [15]:
a * a

array([[ 1,  4],
       [ 9, 16]])

In [16]:
A = np.mat(a)
A

matrix([[1, 2],
        [3, 4]])

In [17]:
(A)

matrix([[1, 2],
        [3, 4]])

In [18]:
A * A

matrix([[ 7, 10],
        [15, 22]])

In [19]:
# executando multiplicação de matriz (dot product) em um array
np.dot(a,a)

array([[ 7, 10],
       [15, 22]])

In [20]:
mat5 = np.asmatrix(a)

In [21]:
mat5

matrix([[1, 2],
        [3, 4]])

In [22]:
mat5 * mat5

matrix([[ 7, 10],
        [15, 22]])

In [25]:
# convertendo de volta para um array
arr2 = np.asarray(mat5)
arr2

array([[1, 2],
       [3, 4]])

In [26]:
arr2 * arr2

array([[ 1,  4],
       [ 9, 16]])