# <font color='blue'>Data Science Academy - Python Fundamentos - Capítulo 8</font>

## Download: http://github.com/dsacademybr

In [ ]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

### Exercícios Sobre Módulos Python Para Análise de Dados

In [23]:
import numpy as np
import pandas as pd
import time
from numpy import random

### ****** ATENÇÃO ******
### Alguns dos exercícios podem requerer pesquisa adicional na documentação dos pacotes. Pesquise!

### Exercício 1

In [14]:
# Crie um array NumPy com 1000000 e uma lista com 1000000.
# Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).
# Qual objeto oferece melhor performance, array NumPy ou lista?

npArray = np.arange(1000000)
array = range(1000000)
print(type(npArray))
print(type(array))

<class 'numpy.ndarray'>
<class 'range'>


In [6]:
start_time = time.time()
npArray * 2
print("----%s seconds ----" % (time.time() - start_time))

----0.003410816192626953 seconds ----


In [17]:
start_time = time.time()
for x in array:
    (x * 2)
    
print("----%s seconds ----" % (time.time() - start_time))

----0.07563900947570801 seconds ----


### Exercício 2

In [18]:
# Exercício 2
# Crie um array de 10 elementos
# Altere o valores de todos os elementos dos índices 5 a 8 para 0
arr10 = np.arange(10)

In [20]:
arr10[5:8] = 0

In [21]:
arr10

array([0, 1, 2, 3, 4, 0, 0, 0, 8, 9])

### Exercício 3

In [38]:
# Crie um array de 3 dimensões e imprima a dimensão 1 

m = np.matrix(np.array([[random.rand(5)],[random.rand(5)],[random.rand(5)]]))
m[1]

matrix([[0.47074142, 0.53999734, 0.58418845, 0.27916822, 0.09562652]])

### Exercício 4

In [55]:
# Crie um array de duas dimensões (matriz).
# Imprima os elementos da terceira linha da matriz
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas

m2 = np.matrix(np.array([[random.rand(5)],[random.rand(5)],[random.rand(5)]]))
m2

matrix([[0.78700388, 0.15535364, 0.15408646, 0.525122  , 0.55057447],
        [0.56004776, 0.75781828, 0.37905377, 0.61045326, 0.30458837],
        [0.84549497, 0.77174773, 0.86371637, 0.1747535 , 0.67561922]])

In [56]:
m2[2]

matrix([[0.84549497, 0.77174773, 0.86371637, 0.1747535 , 0.67561922]])

In [59]:
m2[:2,1:]

matrix([[0.15535364, 0.15408646, 0.525122  , 0.55057447],
        [0.75781828, 0.37905377, 0.61045326, 0.30458837]])

### Exercício 5

In [60]:
# Calcule a transposta da matriz abaixo
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [68]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [69]:
arr.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

### Exercício 6

In [70]:
# Considere os 3 arrays abaixo
# Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr.
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [71]:
for x,y,c in zip(xarr,yarr,cond):
    print(x,y,c)

1.1 2.1 True
1.2 2.2 False
1.3 2.3 True
1.4 2.4 True
1.5 2.5 False


In [73]:
[(x if c else y) for x,y,c in zip(xarr,yarr,cond)]

[1.1, 2.2, 1.3, 1.4, 2.5]

### Exercício 7

In [74]:
# Crie um array A com 10 elementos e salve o array em disco com a extensão npy
# Depois carregue o array do disco no array B

np10 = np.arange(10)
np.save('arr', np10)

In [76]:
np.load('arr.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Exercício 8

In [78]:
# Considerando a série abaixo, imprima os valores únicos na série
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])

obj.unique()

array(['c', 'a', 'd', 'b'], dtype=object)

### Exercício 9

In [79]:
# Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

<Response [200]>

In [88]:
data = resp.json()

In [90]:
pd.DataFrame(data, columns=['number','title', 'labels','state'])

number                                              title  \
0    42017  DOC: Fix wrongly associated docstring of Serie...   
1    42016  BUG: groupby with dropna=False and 'unique' ag...   
2    42015  DOC: pandas.Series.str.isspace has wrong docum...   
3    42014  BUG: `Styler.apply` consistently manages Serie...   
4    42013  Updated the docstring for reset_index in frame.py   
5    42012         ENH/PERF: optional mask in nullable dtypes   
6    42009                    DOC: Add New Community Tutorial   
7    42008  CLN: Verify non-ndarray is an ExtensionArray i...   
8    42007  ENH: Clarify error message when reindexing fai...   
9    42006  DEP: move pkg_resources back inline in functio...   
10   42005  BUG: `DataFrame.apply` labelling index and col...   
11   42003  BUG: 1.3.0rc1 pd.util.hash_array on Index fail...   
12   42002  BUG/TYP: 1.3.0 index.values returns ExtensionA...   
13   42001  BUG: `DataFrame.apply` forces consistent dtype...   
14   42000  ENH: Clarify error message when reindexing on ...   
15   41999  BUG?: 1.3 behavior change with groupby, apply ...   
16   41998  BUG?: 1.3 behavior change with groupby and asi...   
17   41997  1.3: (intended?) Behavior change with empty apply   
18   41996  ENH: Gather `dtype` and `convertors` processin...   
19   41995  [WIP] ENH: `Styler.apply(map)_header` made com...   
20   41994  BUG: apply_header styles not universally appli...   
21   41993  [WIP] ENH: `Styler.apply(map)_header` made com...   
22   41991  STYLE: Added from __future__ import annotation...   
23   41990                       CI: troubleshoot py310 build   
24   41989      DEPS: drop Python 3.7 and NumPy 1.17 (#41678)   
25   41988  WIP: BUG: nan-objects lookup fails with Python...   
26   41986  STYLE Investigate restructuredtext_lint as pre...   
27   41985  DOC: update array-like parameters if scalars a...   
28   41982                          TST: fix xpass for M1 Mac   
29   41980                   REF: Refactor assert_index_equal   

                                               labels state  
0                                                  []  open  
1   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
2   [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
3                                                  []  open  
4                                                  []  open  
5   [{'id': 2822342, 'node_id': 'MDU6TGFiZWwyODIyM...  open  
6   [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
7   [{'id': 42670965, 'node_id': 'MDU6TGFiZWw0MjY3...  open  
8                                                  []  open  
9                                                  []  open  
10  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
11  [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
12  [{'id': 2365504893, 'node_id': 'MDU6TGFiZWwyMz...  open  
13  [{'id': 697792067, 'node_id': 'MDU6TGFiZWw2OTc...  open  
14  [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
15  [{'id': 697792067, 'node_id': 'MDU6TGFiZWw2OTc...  open  
16  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
17  [{'id': 697792067, 'node_id': 'MDU6TGFiZWw2OTc...  open  
18  [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
19                                                 []  open  
20  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
21                                                 []  open  
22                                                 []  open  
23  [{'id': 48070600, 'node_id': 'MDU6TGFiZWw0ODA3...  open  
24  [{'id': 76865106, 'node_id': 'MDU6TGFiZWw3Njg2...  open  
25                                                 []  open  
26  [{'id': 106935113, 'node_id': 'MDU6TGFiZWwxMDY...  open  
27                                                 []  open  
28  [{'id': 2628846204, 'node_id': 'MDU6TGFiZWwyNj...  open  
29                                                 []  open

### Exercício 10

In [ ]:
# Crie um banco de dados no SQLite, crie uma tabela, insira registros, 
# consulte a tabela e retorne os dados em dataframe do Pandas

# Fim

### Obrigado - Data Science Academy - <a href="http://facebook.com/dsacademybr">facebook.com/dsacademybr</a>